# -*- coding: utf-8 -*-
"""Python_HW1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18q9auHU9fxZU6ao-khrXa1oYnQAp-2ss
"""

drone_list = ["DJI Mavic 2 Pro", "DJI Mavic 2 Zoom", "DJI Mavic 2 Enterprise Advanced", "AUTEL Evo II Pro", "DJI Mini 2", "Autel Evo Nano", "Autel Evo Lite Plus", "Parrot Anafi", "Dji Inspire 2", "DJI Mavic 3", "DJI Mavic Air2s", "Ryze Tello", "Eachine Trashcan"]

drone_weight_list = [903, 900, 920, 980, 249, 249, 600, 540, 1500, 1000, 570, 130, 110]

#в drone по очереди попадает каждый дрон из списка drone_list
for drone in drone_list:
	print(drone)

#TODO1
#выведите все дроны производителя, название которого введет пользователь через input, и подсчитайте их количество. 
#учтите, что:
#1) DJI и Dji - это один и тот же производитель! такие случаи тоже должны обрабатываться
#2) при выводе исправьте название производителя, если допущена ошибка. правильный вариант названия: DJI, Autel

company_name = input().lower().strip()
for drone in drone_list:
  drone = drone.strip().split()
  drone[0] = drone[0].lower()
  if drone[0] == company_name:
    drone[0] = drone[0].upper() if drone[0] == "dji" else drone[0].capitalize()
    print(" ".join(drone))

#TODO2
#подсчитайте количество моделей дронов каждого производителя из списка drone_list. производители: DJI, Autel, Parrot, Ryze, Eachine

d = dict((name, set()) for name in ["DJI", "Autel", "Parrot", "Ryze", "Eachine"])
for drone in drone_list:
  drone = drone.strip().split()
  company_name = drone[0].upper() if drone[0].lower() == "dji" else drone[0].capitalize()
  drone[0] = ""
  model_name = " ".join(drone)
  d[company_name].add(model_name)

for i in d:
  print(f"{i}: {len(d[i])}")

#TODO3
#выведите все дроны из списка, которые нужно регистрировать (масса больше 150 г), и подсчитайте их количество. 
#сделайте то же самое для всех дронов, которые не нужно регистрировать
#для этого вам нужно параллельно обрабатывать два списка: drone_list и drone_weight_list:
#как работает zip, мы разберем на лекции про списки. пока что просто пользуйтесь

count = 0
print("Need registration:\n")
for drone, weight in zip(drone_list,  drone_weight_list):
  if weight > 150:
    count += 1
    print(drone, weight)
print(f"\nCount: {count}\n")
 
count = 0
print("\nDo not need registration:\n")
for drone, weight in zip(drone_list,  drone_weight_list):
  if weight <= 150:
    count += 1
    print(drone, weight)
print(f"\nCount: {count}\n")

#TODO4
#для каждого дрона из списка выведите, нужно ли согласовывать полет при следующих условиях:
#высота 100 м, полет над населенным пунктом, вне закрытых зон, в прямой видимости
#помните, что для дронов тяжелее 150 г согласовывать полет над населенным пунктом - обязательно!

drone_height_list = [77, 120, 111, 99, 100, 140, 88, 91, 71, 102, 84, 98, 99]
drone_locality_list = [True, True, False, False, True, True, False, False, True, True, False, True, False]

for drone, weight, height, locality in zip(drone_list,  drone_weight_list, drone_height_list, drone_locality_list):
  if weight <= 150:
    if height > 100:
      res = "cогласование нужно, тк высота более 100 м"
    elif locality == True:
      res = "cогласование нужно, тк полет над населенным пунктом"
    else:
      res = "cогласование не нужно"

  else:
    res = "cогласование нужно, тк вес более 150 г"

  print(f"Дрон ({drone}) с весом ({weight}), требованием по высоте ({height}) и необходимостью пролета над нас.пунктом ({locality})\nРезультат: {res}\n")

#TODO5*
#модифицируйте решение задания TODO1:
#теперь для введенного пользователем производителя вы должны вывести строку, содержащую перечисление моделей и БЕЗ названия производителя.
#например, пользователь ввел "Autel". ваша программа должна вывести вот такой результат: "Evo II Pro, Evo Nano, Evo Lite Plus". для этого вам понадобится несколько функций работы со строками. решить эту задачу можно несколькими разными способами
#производители те же: DJI, Autel, Parrot, Ryze, Eachine

res = []
company_name = input().lower().strip()
for drone in drone_list:
  drone = drone.strip().split()
  if drone[0].lower() == company_name:
    drone.remove(drone[0])
    res.append(" ".join(drone))

", ".join(res)